### Perceptron

In [1]:
import numpy as np

In [43]:
def perceptron(w, x, y, i, iteration, max_i):
    """
    function emulating the logic of perceptron
    
    loss function is calculated as [[ y_i*(w dot x_i + b) <= 0 ]]
    if misclassified (loss == True), adjust weights and bias
    call the algorithm recursively until 'max_iterations' is reached
    
    param: w   -- np.array -- vector of weights (free term 'b' is included)
    param: x   -- np.array -- array of vectors (arrays) of inputs
                              (free term 'b' is included)
    param: y   -- boolean  -- array of labelled results
    param: i   -- int      -- current data point
    param: iteration -- int -- current iteration of the algorithm
    
    global variable: losses -- int -- number of losses 
                                      (updated by this function)
    global variable: runs -- int -- number of iterations
                                      (updated by this function)
    
    returns: perceptron(w, x, y, i) -- recursively calls itself
                                                  until 'max_iterations'
                                                  is reached
    """
    # global variables -- number of losses, number of runs
    global losses, runs
    
    # print headers
    if iteration == 0: print("\n----- Perceptron -----")
    if i == 0: print("\n--- starting a new cycle through data point...")
    
    # classification -- w dot x_i (term 'b' included as last in 'w' and 'x')
    classi = w.dot(x[i])
    
    # calculate the loss function
    loss = y[i] * classi <= 0
    
    print("\n---Iteration #", iteration, ":")
    print("loss({0}) = y_i({1}) * w({2}) dot x_i({3})"
          .format(loss, y[i], w, x[i]))
    print("w dot x_i = ", classi)
    
    # if misclassified, adjust weights
    if loss:
        print("Starting weights:", w)
        w += y[i] * x[i] # adjust vector of weights
        losses += 1
        print("Adjusted wights:", w)
    
    # count iterations
    iteration += 1
    runs = iteration
    # move to next data point
    i += 1
    # reset 'i', if reached the end of 'x'
    if i == len(x):
        print("\n--Cycle completed. From {0:,} records, {1:,}({2:.2f}%) \
were misclassified.".format(i, losses, losses / i * 100))
        if losses == 0:
            print("No records misclasified on this cycle. Exiting...")
            return
        losses = 0 # reset losses for the next cycle
        i = 0      # reset 'i' for the next cycle

    # continue until 'max_iterations' is reached
    if i < max_i:
        return perceptron(w, x, y, i, iteration, max_i)
    else:
        print("Max iterations reached, stopping...")
        return

In [44]:
i = 0                # variable to track current data point
iteration = 0        # starting value for iteration tracking
max_i = 10           # max iterations allowed 
losses = 0           # var to track number of losses per cycle, updated by func
runs = 0             # var to track total number of runs, updated by function

# starting vector of weights 
# (last coordinate represents 'b' from 'w * x_i + b')
w = np.array([0, 0, 0])

# set of vectors of points (last coordinate represents 'b' from 'w * x_i + b')
x = np.array(
    [np.array([-1, 1, 1]),
     np.array([0, -1, 1]),
     np.array([10, 1, 1])]
    )

# set of results
y = np.array([1, -1, 1])

print("Starting weights -- vector w(0):", w)
print("\nData points -- vectors x_i:\n", x)
print("\nResults -- set of y:", y)

perceptron(w, x, y, i, iteration, max_i)

Starting weights -- vector w(0): [0 0 0]

Data points -- vectors x_i:
 [[-1  1  1]
 [ 0 -1  1]
 [10  1  1]]

Results -- set of y: [ 1 -1  1]

----- Perceptron -----

--- starting a new cycle through data point...

---Iteration # 0 :
loss(True) = y_i(1) * w([0 0 0]) dot x_i([-1  1  1])
w dot x_i =  0
Starting weights: [0 0 0]
Adjusted wights: [-1  1  1]

---Iteration # 1 :
loss(True) = y_i(-1) * w([-1  1  1]) dot x_i([ 0 -1  1])
w dot x_i =  0
Starting weights: [-1  1  1]
Adjusted wights: [-1  2  0]

---Iteration # 2 :
loss(True) = y_i(1) * w([-1  2  0]) dot x_i([10  1  1])
w dot x_i =  -8
Starting weights: [-1  2  0]
Adjusted wights: [9 3 1]

--Cycle completed. From 3 records, 3(100.00%) were misclassified.

--- starting a new cycle through data point...

---Iteration # 3 :
loss(True) = y_i(1) * w([9 3 1]) dot x_i([-1  1  1])
w dot x_i =  -5
Starting weights: [9 3 1]
Adjusted wights: [8 4 2]

---Iteration # 4 :
loss(False) = y_i(-1) * w([8 4 2]) dot x_i([ 0 -1  1])
w dot x_i =  -2

---