### Perceptron

In [1]:
import numpy as np

In [7]:
def perceptron(w, x, y, i):
    """
    function emulating the logic of perceptron
    
    loss function is calculated as [[ y_i*(w dot x_i + b) <= 0 ]]
    if misclassified (loss == True), adjust weights and bias
    
    param: w   -- np.array -- vector of weights (free term 'b' is included)
    param: x   -- np.array -- array of vectors (arrays) of inputs
                              (free term 'b' is included)
    param: y   -- boolean  -- array of labelled results
    param: i   -- int      -- current iteration of the algorithm
    
    returns: perceptron(w, x, y, i) -- recursively calls itself
                                                  until 'max_iterations'
                                                  is reached
    """
    loss = y[i] * w.dot(x[i]) <= 0
    print("\n---Iteration #", i, ":")
    print("loss({0}) = y_i({1}) * w({2}) dot x_i({3})"
          .format(loss, y[i], w, x[i]))
    if loss:
        print("Starting weights:", w)
        w += y[i] * x[i] # adjust vector of weights
        w[-1] += y[i]   # adjust element corresponding to bias 'b'
        print("Adjusted wights:", w)
    i += 1
    if i < max_iterations:
        return perceptron(w, x, y, i)
    else:
        print("Max iterations reached, stopping...")
        return

In [8]:
i = 0                # starting value for iteration tracking
max_iterations = 10  # max iterations allowed 

# starting vector of weights 
# (last coordinate represents 'b' from 'w * x_i + b')
w = np.array([0, 0, 0])

# set of vectors of points (last coordinate represents 'b' from 'w * x_i + b')
x = np.array(
    [np.array([-1, 1, 1]),
     np.array([0, -1, 1]),
     np.array([10, 1, 1])]
    )

# set of results
y = np.array([1, -1, 1])

print("Starting weights -- vector w(0):", w)
print("\nData points -- vectors x_i:\n", x)
print("\nResults -- set of y:", y)

perceptron(w, x, y, i)

Starting weights -- vector w(0): [0 0 0]

Data points -- vectors x_i:
 [[-1  1  1]
 [ 0 -1  1]
 [10  1  1]]

Results -- set of y: [ 1 -1  1]

---Iteration # 0 :
loss(True) = y_i(1) * w([0 0 0]) dot x_i([-1  1  1])
Starting weights: [0 0 0]
Adjusted wights: [-1  1  2]

---Iteration # 1 :
loss(True) = y_i(-1) * w([-1  1  2]) dot x_i([ 0 -1  1])
Starting weights: [-1  1  2]
Adjusted wights: [-1  2  0]

---Iteration # 2 :
loss(True) = y_i(1) * w([-1  2  0]) dot x_i([10  1  1])
Starting weights: [-1  2  0]
Adjusted wights: [9 3 2]


IndexError: index 3 is out of bounds for axis 0 with size 3